@echo off
setlocal
set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "ROOT=%%~fI\"
set "MODE=%~1"

REM Tuned production launcher for small VPS targets.
REM Usage:
REM   scripts\start-prod-tuned.bat
REM   scripts\start-prod-tuned.bat loadtest
REM   scripts\start-prod-tuned.bat loadtest-baseline
REM   scripts\start-prod-tuned.bat loadtest-profile
REM
REM Optional env overrides before running:
REM   PORT=5173
REM   HOST=0.0.0.0
REM   GOYLORD_AGENT_TOKEN=change-me
REM   GOYLORD_USER=admin
REM   GOYLORD_PASS=change-me
REM   GOYLORD_TLS_OFFLOAD=false
REM   GOYLORD_HEARTBEAT_INTERVAL_MS=30000
REM   GOYLORD_HEARTBEAT_SWEEP_TICK_MS=1000
REM   GOYLORD_CLIENT_DB_SYNC_MS=15000
REM   GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=100
REM   GOYLORD_CLIENT_PRESENCE_SYNC_MS=60000
REM   GOYLORD_VIEWER_BACKPRESSURE_BYTES=2097152
REM   GOYLORD_MEDIA_VIEWER_BACKPRESSURE_BYTES=524288
REM   GOYLORD_EVENT_LOOP_SAMPLE_MS=100
REM   GOYLORD_EVENT_LOOP_HISTORY_SECONDS=60
REM   GOYLORD_DASHBOARD_DEBOUNCE_MS=1000
REM   GOYLORD_DASHBOARD_EVENT_FLUSH_MS=1000
REM   GOYLORD_DASHBOARD_EVENT_INLINE_LIMIT=20
REM   GOYLORD_OFFLINE_BATCH_SIZE=250
REM   GOYLORD_OFFLINE_BATCH_DELAY_MS=25
REM   GOYLORD_LOAD_TEST_PROFILE=realistic
REM   GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB=true
REM   GOYLORD_THUMBNAILS_DASHBOARD_ENABLED=false
REM   MAX_WS_MESSAGE_BYTES_CLIENT=8388608
REM   MAX_WS_MESSAGE_BYTES_VIEWER=1048576

if not defined HOST set HOST=0.0.0.0
if not defined PORT set PORT=5173
if not defined LOG_LEVEL set LOG_LEVEL=info
if not defined NODE_ENV set NODE_ENV=production

REM Small-host connection tuning. These are conservative for ~250 mostly-idle
REM agents on a 2 vCPU / 2 GB host.
if not defined GOYLORD_HEARTBEAT_INTERVAL_MS set GOYLORD_HEARTBEAT_INTERVAL_MS=30000
if not defined GOYLORD_HEARTBEAT_SWEEP_TICK_MS set GOYLORD_HEARTBEAT_SWEEP_TICK_MS=1000
if not defined GOYLORD_CLIENT_DB_SYNC_MS set GOYLORD_CLIENT_DB_SYNC_MS=15000
if not defined GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE set GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=100
if not defined GOYLORD_CLIENT_PRESENCE_SYNC_MS set GOYLORD_CLIENT_PRESENCE_SYNC_MS=60000
if not defined GOYLORD_VIEWER_BACKPRESSURE_BYTES set GOYLORD_VIEWER_BACKPRESSURE_BYTES=2097152
if not defined GOYLORD_MEDIA_VIEWER_BACKPRESSURE_BYTES set GOYLORD_MEDIA_VIEWER_BACKPRESSURE_BYTES=524288
if not defined GOYLORD_EVENT_LOOP_SAMPLE_MS set GOYLORD_EVENT_LOOP_SAMPLE_MS=100
if not defined GOYLORD_EVENT_LOOP_HISTORY_SECONDS set GOYLORD_EVENT_LOOP_HISTORY_SECONDS=60
if not defined GOYLORD_DASHBOARD_DEBOUNCE_MS set GOYLORD_DASHBOARD_DEBOUNCE_MS=1000
if not defined GOYLORD_DASHBOARD_EVENT_FLUSH_MS set GOYLORD_DASHBOARD_EVENT_FLUSH_MS=1000
if not defined GOYLORD_DASHBOARD_EVENT_INLINE_LIMIT set GOYLORD_DASHBOARD_EVENT_INLINE_LIMIT=20
if not defined GOYLORD_OFFLINE_BATCH_SIZE set GOYLORD_OFFLINE_BATCH_SIZE=250
if not defined GOYLORD_OFFLINE_BATCH_DELAY_MS set GOYLORD_OFFLINE_BATCH_DELAY_MS=25
if not defined GOYLORD_STALE_MS set GOYLORD_STALE_MS=120000
if not defined GOYLORD_DISCONNECT_TIMEOUT_MS set GOYLORD_DISCONNECT_TIMEOUT_MS=10000
if not defined PRUNE_BATCH set PRUNE_BATCH=250
if not defined MAX_WS_MESSAGE_BYTES_CLIENT set MAX_WS_MESSAGE_BYTES_CLIENT=8388608
if not defined MAX_WS_MESSAGE_BYTES_VIEWER set MAX_WS_MESSAGE_BYTES_VIEWER=1048576
if not defined GOYLORD_WS_UPGRADE_RATE_WINDOW_MS set GOYLORD_WS_UPGRADE_RATE_WINDOW_MS=10000
set GOYLORD_PROFILE_SOURCE_MODE=false

REM Keep proxy trust disabled unless the deploy explicitly opts into it.
if not defined GOYLORD_TLS_OFFLOAD set GOYLORD_TLS_OFFLOAD=false
if not defined GOYLORD_TRUST_PROXY set GOYLORD_TRUST_PROXY=false
if not defined GOYLORD_TRUST_PROXY_HEADERS set GOYLORD_TRUST_PROXY_HEADERS=false
if not defined GOYLORD_AUTH_COOKIE_SECURE set GOYLORD_AUTH_COOKIE_SECURE=auto

if /I "%MODE%"=="loadtest" (
  if not defined GOYLORD_AGENT_TOKEN (
    echo [error] loadtest mode requires GOYLORD_AGENT_TOKEN to be set.
    echo Example:
    echo   set GOYLORD_AGENT_TOKEN=some-long-random-token
    echo   scripts\start-prod-tuned.bat loadtest
    endlocal
    exit /b 1
  )
  set GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS=true
  if not defined GOYLORD_LOAD_TEST_PROFILE set GOYLORD_LOAD_TEST_PROFILE=realistic
  if not defined GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS set GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS=false
  if not defined GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB set GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB=true
  if "%GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE%"=="100" set GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=500
  if not defined GOYLORD_WS_UPGRADE_RATE_MAX set GOYLORD_WS_UPGRADE_RATE_MAX=2000
  if not defined GOYLORD_THUMBNAILS_DASHBOARD_ENABLED set GOYLORD_THUMBNAILS_DASHBOARD_ENABLED=false
) else if /I "%MODE%"=="loadtest-profile" (
  if not defined GOYLORD_AGENT_TOKEN (
    echo [error] loadtest-profile mode requires GOYLORD_AGENT_TOKEN to be set.
    echo Example:
    echo   set GOYLORD_AGENT_TOKEN=some-long-random-token
    echo   scripts\start-prod-tuned.bat loadtest-profile
    endlocal
    exit /b 1
  )
  set GOYLORD_PROFILE_SOURCE_MODE=true
  set GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS=true
  if not defined GOYLORD_LOAD_TEST_PROFILE set GOYLORD_LOAD_TEST_PROFILE=realistic
  if not defined GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS set GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS=false
  if not defined GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB set GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB=true
  if "%GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE%"=="100" set GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=500
  if not defined GOYLORD_WS_UPGRADE_RATE_MAX set GOYLORD_WS_UPGRADE_RATE_MAX=2000
  if not defined GOYLORD_THUMBNAILS_DASHBOARD_ENABLED set GOYLORD_THUMBNAILS_DASHBOARD_ENABLED=false
) else if /I "%MODE%"=="loadtest-baseline" (
  if not defined GOYLORD_AGENT_TOKEN (
    echo [error] loadtest-baseline mode requires GOYLORD_AGENT_TOKEN to be set.
    echo Example:
    echo   set GOYLORD_AGENT_TOKEN=some-long-random-token
    echo   scripts\start-prod-tuned.bat loadtest-baseline
    endlocal
    exit /b 1
  )
  set GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS=true
  if not defined GOYLORD_LOAD_TEST_PROFILE set GOYLORD_LOAD_TEST_PROFILE=baseline
  if not defined GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS set GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS=true
  if not defined GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB set GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB=true
  if "%GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE%"=="100" set GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=500
  if not defined GOYLORD_WS_UPGRADE_RATE_MAX set GOYLORD_WS_UPGRADE_RATE_MAX=2000
  if not defined GOYLORD_THUMBNAILS_DASHBOARD_ENABLED set GOYLORD_THUMBNAILS_DASHBOARD_ENABLED=false
) else (
  set GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS=false
  if not defined GOYLORD_WS_UPGRADE_RATE_MAX set GOYLORD_WS_UPGRADE_RATE_MAX=30
)

echo === Goylord tuned production server ===
echo HOST=%HOST%
echo PORT=%PORT%
echo NODE_ENV=%NODE_ENV%
echo LOG_LEVEL=%LOG_LEVEL%
echo GOYLORD_HEARTBEAT_INTERVAL_MS=%GOYLORD_HEARTBEAT_INTERVAL_MS%
echo GOYLORD_HEARTBEAT_SWEEP_TICK_MS=%GOYLORD_HEARTBEAT_SWEEP_TICK_MS%
echo GOYLORD_CLIENT_DB_SYNC_MS=%GOYLORD_CLIENT_DB_SYNC_MS%
echo GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE=%GOYLORD_CLIENT_DB_SYNC_BATCH_SIZE%
echo GOYLORD_CLIENT_PRESENCE_SYNC_MS=%GOYLORD_CLIENT_PRESENCE_SYNC_MS%
echo GOYLORD_VIEWER_BACKPRESSURE_BYTES=%GOYLORD_VIEWER_BACKPRESSURE_BYTES%
echo GOYLORD_MEDIA_VIEWER_BACKPRESSURE_BYTES=%GOYLORD_MEDIA_VIEWER_BACKPRESSURE_BYTES%
echo GOYLORD_EVENT_LOOP_SAMPLE_MS=%GOYLORD_EVENT_LOOP_SAMPLE_MS%
echo GOYLORD_EVENT_LOOP_HISTORY_SECONDS=%GOYLORD_EVENT_LOOP_HISTORY_SECONDS%
echo GOYLORD_DASHBOARD_DEBOUNCE_MS=%GOYLORD_DASHBOARD_DEBOUNCE_MS%
echo GOYLORD_DASHBOARD_EVENT_FLUSH_MS=%GOYLORD_DASHBOARD_EVENT_FLUSH_MS%
echo GOYLORD_DASHBOARD_EVENT_INLINE_LIMIT=%GOYLORD_DASHBOARD_EVENT_INLINE_LIMIT%
echo GOYLORD_OFFLINE_BATCH_SIZE=%GOYLORD_OFFLINE_BATCH_SIZE%
echo GOYLORD_OFFLINE_BATCH_DELAY_MS=%GOYLORD_OFFLINE_BATCH_DELAY_MS%
echo MAX_WS_MESSAGE_BYTES_CLIENT=%MAX_WS_MESSAGE_BYTES_CLIENT%
echo MAX_WS_MESSAGE_BYTES_VIEWER=%MAX_WS_MESSAGE_BYTES_VIEWER%
echo GOYLORD_WS_UPGRADE_RATE_MAX=%GOYLORD_WS_UPGRADE_RATE_MAX%
echo GOYLORD_WS_UPGRADE_RATE_WINDOW_MS=%GOYLORD_WS_UPGRADE_RATE_WINDOW_MS%
echo GOYLORD_TLS_OFFLOAD=%GOYLORD_TLS_OFFLOAD%
echo GOYLORD_TRUST_PROXY=%GOYLORD_TRUST_PROXY%
echo GOYLORD_TRUST_PROXY_HEADERS=%GOYLORD_TRUST_PROXY_HEADERS%
echo GOYLORD_AUTH_COOKIE_SECURE=%GOYLORD_AUTH_COOKIE_SECURE%
echo GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS=%GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS%
echo GOYLORD_LOAD_TEST_PROFILE=%GOYLORD_LOAD_TEST_PROFILE%
echo GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS=%GOYLORD_LOAD_TEST_SKIP_SIDE_EFFECTS%
echo GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB=%GOYLORD_LOAD_TEST_DEFER_SYNTHETIC_DB%
echo GOYLORD_THUMBNAILS_DASHBOARD_ENABLED=%GOYLORD_THUMBNAILS_DASHBOARD_ENABLED%
echo GOYLORD_PROFILE_SOURCE_MODE=%GOYLORD_PROFILE_SOURCE_MODE%
echo.

if /I "%GOYLORD_LOAD_TEST_ALLOW_UNSIGNED_AGENTS%"=="true" (
  echo [warning] Synthetic unsigned load-test agents are enabled.
  echo [warning] Do not use this mode for public production traffic.
  echo.
)

pushd "%ROOT%Goylord-Server"
echo [build] installing deps...
call bun install
if errorlevel 1 goto :err

if /I "%GOYLORD_PROFILE_SOURCE_MODE%"=="true" (
  echo [build] building server assets for source-profile mode...
  call bun run build:css
  if errorlevel 1 goto :err
  call bun run vendor
  if errorlevel 1 goto :err
) else (
  echo [build] building server assets and bundle...
  call bun run build
  if errorlevel 1 goto :err
)

if /I "%GOYLORD_PROFILE_SOURCE_MODE%"=="true" (
  echo [build] skipping compiled executable so profiler keeps source function names.
) else (
  echo [build] compiling Windows production executable...
  call bun run build:prod:win
  if errorlevel 1 goto :err
)

echo [build] copying Goylord-Client source for runtime builds...
robocopy "%ROOT%Goylord-Client" "%ROOT%Goylord-Server\dist\Goylord-Client" /E /XD build .git .vscode /NFL /NDL /NJH /NJS >nul
if errorlevel 8 goto :err

set "GOYLORD_ROOT=%ROOT%Goylord-Server"
if /I "%GOYLORD_PROFILE_SOURCE_MODE%"=="true" (
  echo [server] starting source-profile server with Bun...
  call bun src/index.ts
) else (
  echo [server] starting compiled production server...
  call "%ROOT%Goylord-Server\dist\goylord-server.exe"
)
popd

echo Server stopped.
endlocal
exit /b 0

:err
popd >nul 2>&1
echo [error] Production start failed.
endlocal
exit /b 1
